services:
  - type: web
    name: workpulse-api
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: ConnectionStrings__DefaultConnection
        fromDatabase:
          name: workpulse-db
          property: connectionString
      - key: Jwt__Secret
        generateValue: true
      - key: Jwt__Issuer
        value: WorkPulseApi
      - key: Jwt__Audience
        value: WorkPulseApp
      - key: AllowedOrigins__0
        value: https://workpulse-api-mbco.onrender.com
      - key: AllowedOrigins__1
        value: https://workpulse.vercel.app
      - key: FrontendBaseUrl
        value: https://workpulse.vercel.app
      - key: Google__ClientId
        sync: false
      - key: Google__ClientSecret
        sync: false
      - key: Google__RedirectUri
        value: https://workpulse-api-mbco.onrender.com/api/googledrive/callback
      - key: ASPNETCORE_ENVIRONMENT
        value: Production

databases:
  - name: workpulse-db
    plan: free
    databaseName: workpulse
    user: workpulse_user
