using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using WorkPulse.Api.Data;
using WorkPulse.Api.Mapping;
using WorkPulse.Models;

namespace WorkPulse.Api.Controllers;

/// <summary>
/// In-app notifications generated by NotificationTriggerService (daily report reminders, upcoming
/// trips, ...). Read-only from the client's perspective beyond marking items read — generation
/// happens entirely server-side on a schedule.
/// </summary>
[Route("api/[controller]")]
public class NotificationsController : ApiControllerBase
{
    private readonly AppDbContext _db;

    public NotificationsController(AppDbContext db)
    {
        _db = db;
    }

    [HttpGet]
    public async Task<ActionResult<List<AppNotification>>> GetAll()
    {
        var notifications = await _db.Notifications
            .Where(n => n.UserId == UserId)
            .OrderByDescending(n => n.CreatedUtc)
            .Take(30)
            .ToListAsync();

        return Ok(notifications.Select(n => n.ToDto()).ToList());
    }

    [HttpPost("{id}/read")]
    public async Task<IActionResult> MarkRead(string id)
    {
        var notification = await _db.Notifications.FirstOrDefaultAsync(n => n.Id == id && n.UserId == UserId);
        if (notification is null) return NotFound();

        notification.ReadUtc ??= DateTime.UtcNow;
        await _db.SaveChangesAsync();
        return Ok(notification.ToDto());
    }

    [HttpPost("read-all")]
    public async Task<IActionResult> MarkAllRead()
    {
        var unread = await _db.Notifications.Where(n => n.UserId == UserId && n.ReadUtc == null).ToListAsync();
        var now = DateTime.UtcNow;
        foreach (var n in unread) n.ReadUtc = now;
        await _db.SaveChangesAsync();
        return NoContent();
    }
}
