<Project Sdk="Microsoft.NET.Sdk.BlazorWebAssembly">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Blazored.LocalStorage" Version="4.5.0" />
    <PackageReference Include="Microsoft.AspNetCore.Components.Authorization" Version="8.0.*" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" Version="8.0.23" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.DevServer" Version="8.0.23" PrivateAssets="all" />
    <PackageReference Include="Microsoft.Extensions.Http" Version="8.0.*" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.0.*" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\WorkPulse.Shared\WorkPulse.Shared.csproj" />
  </ItemGroup>

  <!-- Tailwind CSS build -->
  <Target Name="BuildTailwind" BeforeTargets="Build">
    <Exec Command="npm install" WorkingDirectory="$(MSBuildProjectDirectory)" />
    <Exec Command="npm run css:build" WorkingDirectory="$(MSBuildProjectDirectory)" />
  </Target>

</Project>
